layout_spectrum: 0.4044519
typography_spectrum: 0.7382919
color:
  saturation: 0.6693087
  lightness: 0.4270299
  brandStrength: 0.2102851
  rhythmicContrast: 0.7088808
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Peregrino
